version: '3.3'
services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql/data
